### ISSUE TITLE
Nota de caracter informativo

### ISSUE THREAD

**Issue by gaal1le0** [ismabk/funcionesJava#1]
https://github.com/ismabk/funcionesJava/blob/44897314472a9fbb544c65d08911312b50a63da2/index.js#L43

Está bastante bien tu código, pero de cara a mejorar, para eliminar los elementos repetidos de un array puedes usar tecnología pura de JS y en 1-2 lineas limpiar el array.
¿Cómo?
Bien sencillo :) usando `Set`

```js
let newArray = new Set(arr);
return [...newArray];
```

Con esto que ves aquí ya he eliminado todas las repeticiones en tan solo 2 líneas de código y de una manera optima. Para que sepas porque, un set es una colección de objetos, en este caso de string pero que no pueden estar repetidos. 
¿Pero, como se asegura JS que no están repetidos?
Sencillo, cada elemento tiene un HASH único que lo representa y cuando se crea un set el propio JS se fija que no exista un elemento dentro con el HASH del elemento que se está intentando añadir.

Y lo ultimo, lo que hace es colocar en un array (ya que debes devolver un array) todos los elementos que están dentro del SET.

**Comment by ismabk** [comment]
Buenas Manu que tal, si sabía que con set se podía llegar a hacer, de echo
si recuerdas fue lo que te pregunte si el método set era válido y me
dijiste que si, que estaba con Isaac y Jesús y entraste y fue cuando te
pregunte. Pero como ya lo tenía con indexOf lo deje así porque la forma del
set no se me ocurrió hasta que hable con Isaac y no veía mejor la manera en
la que lo conseguí sacar de mi manera. Aunque ya si sabía que lo podía
cambiar. Te respondo por aquí porque no me sale ningún issue en GitHub no
se porque.
Muchas gracias por todo un saludo.

**Comment by gaal1le0** [comment]
Okey perfecto. Todo okey
